fieldLayouts:
  2f9f8dd4-2a81-4a1e-a221-a7a686ed730f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e126101-6a91-4330-a6a2-8b3852efba17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 595cda13-61f2-4114-a6a8-6516833e930b # release
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a64ad036-5f75-49ea-bd66-39da8bb3ab48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ee70234-c80f-4f11-8cc1-698b4943fd6c # artists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b63a8b2-4a27-40e6-bfb2-26b691acb40f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2053e87c-59f8-4df9-8204-e3e1935f9050 # songs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccbeac9f-3c3a-4590-85ca-9426b495fb1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b72536c0-eb90-4332-9c1a-2fb2de79b6bd # bannerImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9a644b0-c818-4201-b069-a0ab0ab8eb65
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 039ab39f-43e8-4a0e-a672-c71a3a87746b
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 61e706d8-85e9-44ba-b43f-9d15cf086ac8 # album
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
