defaultPlacement: end
enableVersioning: true
handle: artist
name: artist
propagationMethod: all
siteSettings:
  c680bc59-3f05-428d-8bc4-bc16533915c2: # WeshMusics
    enabledByDefault: true
    hasUrls: true
    template: artist/_entry
    uriFormat: 'artist/{slug}'
type: channel
